### ISSUE TITLE
Building Movist for first time on El Capitan unable to locate QTKit.h

### ISSUE THREAD

**Issue by davidfavor** [samiamwork/Movist#51]
Unable to locate QTKit.h which does exist on machine.

/System/Library/Frameworks/QTKit.framework/Versions/Current/Headers/QTKit.h is full path to this file.

Let me know best way to fix this.

Thanks.
```
imac> xcodebuild -version
Xcode 8.1
Build version 8B62
```

**Comment by samiamwork** [comment]
You Can remove those lines (Same for Quicktime.h) and it should still compile just fine. I moved the codebase off Quicktime a while ago but I guess I forgot to remove the includes. I'll put up a fix in the next few days but you can just remove them in your copy in the meantime.

Sorry for the late reply!

**Comment by davidfavor** [comment]
Thanks for you're reply!

I'll give it another try shortly.

Also, if you can just drop an update here of when I can do a new git pull, that will be great.

Thanks!

**Comment by samiamwork** [comment]
Okay I've removed the use of the header. I also fixed a bunch of warnings.

**Comment by davidfavor** [comment]
Thanks!

I'll do another pull + let you know how it goes.
