### ISSUE TITLE
Random Tip: Movist requires git clone + won't work with pulling a zip file

### ISSUE THREAD

**Issue by davidfavor** [samiamwork/Movist#53]
I pulled down a zip file the other day + attempted to build it + got all sorts of git related errors.

Best to add to the build instructions, a git clone is required + a git zip file won't work.

Just letting you know.

Thanks for taking over this project!

**Comment by samiamwork** [comment]
Added a error message when you try to build without the git repo. It tells you what you can do to work around it.

**Comment by davidfavor** [comment]
Thanks!
